#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Taken from the modding manual
nations = {
    5: "Arcoscephale", # EA
    6: "Ermor",
    7: "Ulm",
    8: "Marverni",
    9: "Sauromatia",
    10: "T'ien Ch'i",
    11: "Machaka",
    12: "Mictlan",
    13: "Abysia",
    14: "Caelum",
    15: "C'tis",
    16: "Pangaea",
    17: "Agartha",
    18: "Tir na n'Og",
    19: "Fomoria",
    20: "Vanheim",
    21: "Helheim",
    22: "Niefelheim",
    25: "Kailasa",
    26: "Lanka",
    27: "Yomi",
    28: "Hinnom",
    29: "Ur",
    30: "Berytos",
    31: "Xibalba",
    83: "Atlantis",
    84: "R'lyeh",
    85: "Pelagia",
    86: "Oceania",
    33: "Arcoscephale", # MA
    34: "Ermor",
    35: "Sceleria",
    36: "Pythium",
    37: "Man",
    38: "Eriu",
    39: "Ulm",
    40: "Marignon",
    41: "Mictlan",
    42: "T'ien Ch'i",
    43: "Machaka",
    44: "Agartha",
    45: "Abysia",
    46: "Caelum",
    47: "C'tis",
    48: "Pangaea",
    49: "Asphodel",
    50: "Vanheim",
    51: "Jotunheim",
    52: "Vanarus",
    53: "Bandar Log",
    54: "Shinuyama",
    55: "Ashdod",
    87: "Atlantis",
    88: "R'lyeh",
    89: "Pelagia",
    90: "Oceania",
    57: "Nazca",
    58: "Xibalba",
    60: "Arcoscephale", # LA
    61: "Pythium",
    62: "Lemuria",
    63: "Man",
    64: "Ulm",
    65: "Marignon",
    66: "Mictlan",
    67: "T'ien Ch'i",
    69: "Jomon",
    70: "Agartha",
    71: "Abysia",
    72: "Caelum",
    73: "C'tis",
    74: "Pangaea",
    75: "Midgård",
    76: "Utgård",
    77: "Bogarus",
    78: "Patala",
    79: "Gath",
    80: "Ragha",
    91: "Atlantis",
    92: "R'lyeh",
    81: "Xibalba"}